Bike = input('Whats you bike? ')
Name = input('Whas your Name? ')
Name = Name.strip()
Bike = Bike.title()
print(f'My bike is {Bike} and my name is {Name}')
print("My bike is {} and my name is {}".format(Bike, Name))